# Generated by Django 4.1.3 on 2023-02-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('sex', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=3)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('appointment_day', models.DateField()),
                ('appointment_time', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.service')),
            ],
        ),
    ]
